use_frameworks!

target 'RunicPromises_Example' do
  pod 'RunicPromises', :path => '../'

  target 'RunicPromises_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
